# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1-stretch
        environment: 
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: android-tonespy
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: android-tonespy
          POSTGRES_DB: mentor_database_test
          POSTGRES_PASSWORD: ""
          DATABASE_TEST_URL: "postgres://android-tonespy@localhost:5432/mentor_database_test"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
        
      # run db migration
      - run: node_modules/.bin/sequelize db:migrate
        environment:
          DATABASE_TEST_URL: "postgres://android-tonespy@localhost:5432/mentor_database_test"
            
      # run tests!
      - run: yarn test
